import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { execFileSync } from 'node:child_process';

const APP_PATH = '/Applications/Paneful.app';
const BUNDLE_ID = 'com.paneful.app';

function findIconSource(): string | null {
  // From compiled dist/server/ → ../web/icon-512.png
  const distIcon = path.resolve(import.meta.dirname, '..', 'web', 'icon-512.png');
  if (fs.existsSync(distIcon)) return distIcon;

  // From dev server/ → web/public/icon-512.png
  const devIcon = path.resolve(import.meta.dirname, '..', 'web', 'public', 'icon-512.png');
  if (fs.existsSync(devIcon)) return devIcon;

  return null;
}

function buildIcns(pngPath: string, contentsDir: string): string | null {
  const iconsetDir = path.join(os.tmpdir(), 'Paneful.iconset');
  const icnsPath = path.join(contentsDir, 'Resources', 'Paneful.icns');

  try {
    fs.mkdirSync(iconsetDir, { recursive: true });

    // sips to create required icon sizes
    const sizes = [16, 32, 64, 128, 256, 512];
    for (const size of sizes) {
      const outFile = path.join(iconsetDir, `icon_${size}x${size}.png`);
      execFileSync('sips', ['-z', String(size), String(size), pngPath, '--out', outFile], { stdio: 'pipe' });

      // @2x variant (retina) for half-size key
      if (size >= 32) {
        const halfKey = size / 2;
        const retinaFile = path.join(iconsetDir, `icon_${halfKey}x${halfKey}@2x.png`);
        if (!fs.existsSync(retinaFile)) {
          fs.copyFileSync(outFile, retinaFile);
        }
      }
    }

    fs.mkdirSync(path.dirname(icnsPath), { recursive: true });
    execFileSync('iconutil', ['-c', 'icns', iconsetDir, '-o', icnsPath], { stdio: 'pipe' });

    // Cleanup
    fs.rmSync(iconsetDir, { recursive: true, force: true });

    return icnsPath;
  } catch {
    // Cleanup on failure
    try { fs.rmSync(iconsetDir, { recursive: true, force: true }); } catch { /* ok */ }
    return null;
  }
}

function getInfoPlist(hasIcon: boolean): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key>
  <string>Paneful</string>
  <key>CFBundleDisplayName</key>
  <string>Paneful</string>
  <key>CFBundleIdentifier</key>
  <string>${BUNDLE_ID}</string>
  <key>CFBundleVersion</key>
  <string>1.0</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleExecutable</key>
  <string>Paneful</string>
${hasIcon ? `  <key>CFBundleIconFile</key>
  <string>Paneful</string>
` : ''}</dict>
</plist>
`;
}

function getLauncherScript(): string {
  // Bake in current paths at install time
  const bakedNode = process.execPath;
  const bakedPaneful = fs.realpathSync(process.argv[1]);

  return `#!/bin/bash
# Paneful.app launcher — generated by paneful --install-app
# Baked paths (fast path), with runtime fallbacks

LOG="$HOME/.paneful/app.log"
mkdir -p "$HOME/.paneful"
exec >> "$LOG" 2>&1
echo "--- $(date) ---"

BAKED_NODE="${bakedNode}"
BAKED_PANEFUL="${bakedPaneful}"

find_node() {
  # 1. Baked path
  if [[ -x "$BAKED_NODE" ]]; then echo "$BAKED_NODE"; return; fi

  # 2. Common locations
  for p in /usr/local/bin/node /opt/homebrew/bin/node; do
    if [[ -x "$p" ]]; then echo "$p"; return; fi
  done

  # 3. nvm
  if [[ -d "$HOME/.nvm/versions/node" ]]; then
    local latest
    latest=$(ls -1d "$HOME/.nvm/versions/node"/v* 2>/dev/null | sort -V | tail -1)
    if [[ -x "$latest/bin/node" ]]; then echo "$latest/bin/node"; return; fi
  fi

  # 4. fnm
  if [[ -d "$HOME/.fnm" ]]; then
    local latest
    latest=$(ls -1d "$HOME/.fnm/node-versions"/v* 2>/dev/null | sort -V | tail -1)
    if [[ -x "$latest/installation/bin/node" ]]; then echo "$latest/installation/bin/node"; return; fi
  fi

  # 5. volta
  if [[ -x "$HOME/.volta/bin/node" ]]; then echo "$HOME/.volta/bin/node"; return; fi

  # 6. Parse shell config PATH exports
  for rc in "$HOME/.zshrc" "$HOME/.bash_profile" "$HOME/.bashrc" "$HOME/.zprofile"; do
    if [[ -f "$rc" ]]; then
      while IFS= read -r line; do
        if [[ "$line" =~ ^export\\ +PATH=.*|^PATH= ]]; then
          local extracted
          extracted=$(echo "$line" | sed 's/.*PATH=["]*//;s/["]*$//' | tr ':' '\\n' | sed "s|\\$HOME|$HOME|g;s|~|$HOME|g")
          while IFS= read -r dir; do
            dir=$(eval echo "$dir" 2>/dev/null)
            if [[ -x "$dir/node" ]]; then echo "$dir/node"; return; fi
          done <<< "$extracted"
        fi
      done < "$rc"
    fi
  done

  return 1
}

find_paneful() {
  # 1. Baked path
  if [[ -f "$BAKED_PANEFUL" ]]; then echo "$BAKED_PANEFUL"; return; fi

  # 2. Common global bin locations
  for p in /usr/local/bin/paneful /opt/homebrew/bin/paneful; do
    if [[ -x "$p" ]]; then
      # Resolve symlink to get the actual .js file
      local resolved
      resolved=$(readlink -f "$p" 2>/dev/null || readlink "$p" 2>/dev/null || echo "$p")
      echo "$resolved"; return
    fi
  done

  # 3. npm global prefix
  local node_bin
  node_bin=$(dirname "$1")
  if [[ -x "$node_bin/paneful" ]]; then
    local resolved
    resolved=$(readlink -f "$node_bin/paneful" 2>/dev/null || readlink "$node_bin/paneful" 2>/dev/null || echo "$node_bin/paneful")
    echo "$resolved"; return
  fi

  return 1
}

show_error() {
  osascript -e "display dialog \\"$1\\" with title \\"Paneful\\" buttons {\\"OK\\"} default button \\"OK\\" with icon stop" 2>/dev/null
}

NODE=$(find_node)
if [[ -z "$NODE" ]]; then
  echo "ERROR: node not found"
  show_error "Could not find Node.js.\\n\\nInstall Node.js and run: paneful --install-app"
  exit 1
fi
echo "Using node: $NODE"

PANEFUL=$(find_paneful "$NODE")
if [[ -z "$PANEFUL" ]]; then
  echo "ERROR: paneful not found"
  show_error "Could not find paneful.\\n\\nRun: npm install -g paneful && paneful --install-app"
  exit 1
fi
echo "Using paneful: $PANEFUL"

exec "$NODE" "$PANEFUL"
`;
}

export async function installApp(): Promise<void> {
  if (process.platform !== 'darwin') {
    console.error('paneful --install-app is only supported on macOS.');
    process.exit(1);
  }

  console.log('Creating Paneful.app in /Applications...');

  const contentsDir = path.join(APP_PATH, 'Contents');
  const macosDir = path.join(contentsDir, 'MacOS');
  const resourcesDir = path.join(contentsDir, 'Resources');

  try {
    // Create directory structure
    fs.mkdirSync(macosDir, { recursive: true });
    fs.mkdirSync(resourcesDir, { recursive: true });

    // Icon
    const iconSource = findIconSource();
    let hasIcon = false;
    if (iconSource) {
      const icnsPath = buildIcns(iconSource, contentsDir);
      hasIcon = icnsPath !== null;
      if (hasIcon) {
        console.log('  Icon: converted to .icns');
      } else {
        console.log('  Icon: conversion failed, using generic icon');
      }
    } else {
      console.log('  Icon: source not found, using generic icon');
    }

    // Info.plist
    fs.writeFileSync(path.join(contentsDir, 'Info.plist'), getInfoPlist(hasIcon));
    console.log('  Info.plist: written');

    // Launcher script
    const launcherPath = path.join(macosDir, 'Paneful');
    fs.writeFileSync(launcherPath, getLauncherScript());
    fs.chmodSync(launcherPath, 0o755);
    console.log('  Launcher: written');

    // Touch the app so Finder picks up changes
    try {
      execFileSync('touch', [APP_PATH], { stdio: 'pipe' });
    } catch { /* ok */ }

    console.log('\nPaneful.app installed successfully!');
    console.log('You can now launch Paneful from your Applications folder or Dock.');
  } catch (err: unknown) {
    if ((err as NodeJS.ErrnoException).code === 'EACCES') {
      console.error('\nPermission denied. Try:');
      console.error('  sudo paneful --install-app');
      process.exit(1);
    }
    throw err;
  }
}
